from gym_gazebo.envs.pincher_arm.gazebo_smartbot_pincher_kinect import GazeboSmartBotPincherKinectEnv
from gym_gazebo.envs.pincher_arm.gazebo_smartbot_pincher_kinect_REAL_ARM import GazeboSmartBotPincherKinectEnvREAL_ARM
